# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 01:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liga_futsal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='id',
        ),
        migrations.AlterField(
            model_name='match',
            name='match_number',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False),
        ),
    ]
